baseURL = 'https://jordanbchilds.github.io/'
languageCode = 'en-gb'
theme = "PaperMod"
title = "Home"
paginate = 2
publishDir = "docs"
staticDir = ['static']
customCSS = ["css/custom.css"]

[author]
name = "Jordan Childs"
email = "jordanbchilds@gmail.com"

[params]

defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true

images = ["images/profile.JPG"]

[params.homeInfoParams]
Title = "Jordan Childs"

Content = """
Statistics PhD graduate with interests in quantitative analysis,
stochastic modelling, Bayesian inference, and energy markets.

This site contains projects and writing related to:
- Stochastic models
- Monte Carlo simulation
- Bayesian methods
- Time-series analysis
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/jordanbchilds"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/jordan-childs-186613181/?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3Bui3lY0EiQKipvQ8bKOUj1Q%3D%3D"

[[menu.main]]
identifier = "aboutme"
name = "About Me"
url = "/aboutme/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blogs"
url = "/posts/"
weight = 20

ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[markup]
goldmark.renderer.unsafe = true

[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
